const words = [
    'VAST','PILLBOX','CONSTANT','RECKLESS','SMILE','FRANTIC','ELIMINATION','GUTLESS','FUTURELESS','BARON','CONSPIRACY','GLOBAL','DECODE','GREEN','DIFFICULT','ORTHODOX','ADHERENCE','CALCULATION','CUDDLY','COLOR','CAT'
]



module.exports = words